baseURL = "/"
languageCode = "en-us"
title = "archie"
theme = "archie"
copyright = "archie test"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
ignoreErrors = ["error-missing-instagram-accesstoken"]
paginate = 5 # articles per page
enableRobotsTXT = true

# [markup]
#   [markup.highlight]
#     anchorLineNos = false
#     codeFences = true
#     guessSyntax = false
#     hl_Lines = ''
#     lineAnchors = ''
#     lineNoStart = 1
#     lineNos = false
#     lineNumbersInTable = true
#     noClasses = false
#     noHl = false
#     style = 'monokailight'
#     tabWidth = 4

[params]
	mode = "toggle" # color-mode → light,dark,toggle or auto
	useCDN = true # don't use CDNs for fonts and icons, instead serve them locally.

	subtitle = "params.Subtitle contents"
	# Also change the description section of the meta headers

	favicon = "favicon.png"
	description = "params.Subtitle contents"
	facebook = ""
	twitter = ""
	instagram = ""
	youtube = ""
	github = ""
	gitlab = ""
	linkedin = ""
	mastodon = ""
	# choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
	background_color_class = "bg-black"
	featured_image = "/images/gohugo-default-sample-hero-image.jpg"
	recent_posts_number = 2

# Social Tags
[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://linkedin.com/"

# Main menu Items
[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 1

[[menu.main]]
name = "Tags"
url = "/categories"
weight = 3
